spring:
  main:
    banner-mode: off
  application:
    name: internal-mcp-server
  ai:
    mcp:
      server:
        name: internal-mcp-server
        version: 0.1.0
        type: SYNC
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp
        annotation-scanner:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

#logging:
 # level:
  #  root: INFO
    
    # Enable DEBUG logging for the core MCP transport layer
logging:
   level:
      io.modelcontextprotocol.spec: TRACE
      io.modelcontextprotocol.client: TRACE
      io.modelcontextprotocol.client.transport: TRACE
      org.springframework.ai.mcp: TRACE
 